/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.AddItemController;
import Controller.AddToTableController;
import Controller.CreateBrandController;
import Controller.PurchaseController;
import Controller.UpdateController;
import Model.DatabaseOperations;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


        
        
/**
 *
 * @author Adithya
 */
public class Home extends javax.swing.JFrame {
String total = "0";
static boolean auth =false;
static int i = 0;

    
    static DefaultTableModel dtm;
    
    public Home() {
        
        initComponents();
        
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
            dtm = (DefaultTableModel)itemsTbl.getModel();
            dtm.setRowCount(0);
            
         
           ResultSet rs = new UpdateController().updateBrandsCmb();
        brandsCmb.removeAllItems();
      
        try {   
            
            while(rs.next()){
                
                brandsCmb.addItem(rs.getString("table_name").replace('_', ' '));
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            
        }
        
        showItemsBtn.setEnabled(false);
    }
    
    String getCategoryRBtns()
{
    if(mensRBtn.isSelected())
    {
        return "mens";
    }
    else if(ladiesRBtn.isSelected())
    {
        return "ladies";
    }
    else if(kidsRBtn.isSelected())
    {
        return "kids";
    }
    else
    {
        return null;
    }
}
    public static void clearTable(){
    
        // if(auth==false){
            
        
        
        int i = 0;
            while(dtm.getRowCount()>i)
            {dtm.removeRow(i);
            AddToTableController.removefromTable(i);
            }
            
           // auth = true;
       // }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        itemsCmb = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        showItemsBtn = new javax.swing.JButton();
        brandsCmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mensRBtn = new javax.swing.JRadioButton();
        ladiesRBtn = new javax.swing.JRadioButton();
        kidsRBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        noOfItemsSpnr = new javax.swing.JSpinner();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        itemIdTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        availNoOfItemsLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        amountLbl = new javax.swing.JLabel();
        removeBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        createTableMBtn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(229, 228, 226));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 17)); // NOI18N
        jLabel6.setText("Total Amount:");

        itemsTbl.setBackground(new java.awt.Color(96, 130, 182));
        itemsTbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemsTbl.setForeground(new java.awt.Color(239, 238, 236));
        itemsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Brand", "Item Name", "Category", "No. of Items", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemsTbl.setToolTipText("");
        itemsTbl.setGridColor(new java.awt.Color(176, 176, 218));
        itemsTbl.setRowHeight(25);
        itemsTbl.setRowMargin(5);
        itemsTbl.setSelectionBackground(new java.awt.Color(0, 0, 102));
        itemsTbl.setSelectionForeground(new java.awt.Color(242, 233, 232));
        itemsTbl.setShowGrid(false);
        itemsTbl.setShowHorizontalLines(true);
        itemsTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(itemsTbl);
        if (itemsTbl.getColumnModel().getColumnCount() > 0) {
            itemsTbl.getColumnModel().getColumn(0).setPreferredWidth(1);
            itemsTbl.getColumnModel().getColumn(1).setPreferredWidth(6);
            itemsTbl.getColumnModel().getColumn(3).setPreferredWidth(5);
            itemsTbl.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        jPanel3.setBackground(new java.awt.Color(211, 221, 225));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jPanel3AncestorRemoved(evt);
            }
        });
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        itemsCmb.setBackground(new java.awt.Color(234, 245, 249));
        itemsCmb.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemsCmb.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        itemsCmb.setMinimumSize(new java.awt.Dimension(32767, 32767));
        itemsCmb.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                itemsCmbComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                itemsCmbComponentRemoved(evt);
            }
        });
        itemsCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemsCmbItemStateChanged(evt);
            }
        });
        itemsCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsCmbActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(229, 228, 226));
        addBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        addBtn.setText("Add to list");
        addBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addBtn.setFocusPainted(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Item");

        showItemsBtn.setBackground(new java.awt.Color(229, 228, 226));
        showItemsBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        showItemsBtn.setText("Show items");
        showItemsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showItemsBtn.setBorderPainted(false);
        showItemsBtn.setFocusPainted(false);
        showItemsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showItemsBtnMouseClicked(evt);
            }
        });
        showItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showItemsBtnActionPerformed(evt);
            }
        });

        brandsCmb.setBackground(new java.awt.Color(234, 245, 249));
        brandsCmb.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        brandsCmb.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        brandsCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brandsCmbItemStateChanged(evt);
            }
        });
        brandsCmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                brandsCmbMousePressed(evt);
            }
        });
        brandsCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandsCmbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Brand");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Category");

        mensRBtn.setBackground(new java.awt.Color(211, 221, 225));
        buttonGroup1.add(mensRBtn);
        mensRBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        mensRBtn.setText("Men's");
        mensRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensRBtnActionPerformed(evt);
            }
        });

        ladiesRBtn.setBackground(new java.awt.Color(211, 221, 225));
        buttonGroup1.add(ladiesRBtn);
        ladiesRBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        ladiesRBtn.setText("Ladie's");
        ladiesRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladiesRBtnActionPerformed(evt);
            }
        });

        kidsRBtn.setBackground(new java.awt.Color(211, 221, 225));
        buttonGroup1.add(kidsRBtn);
        kidsRBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        kidsRBtn.setText("Kids's");
        kidsRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidsRBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("No. of Items");

        noOfItemsSpnr.setFont(new java.awt.Font("Segoe UI Variable", 0, 13)); // NOI18N
        noOfItemsSpnr.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel4.setText("Item Id:");

        itemIdTF.setBackground(new java.awt.Color(229, 228, 226));
        itemIdTF.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        itemIdTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemIdTF.setCaretColor(new java.awt.Color(246, 184, 121));
        itemIdTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                itemIdTFCaretUpdate(evt);
            }
        });
        itemIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdTFActionPerformed(evt);
            }
        });
        itemIdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemIdTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemIdTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemIdTFKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel12.setText("Price:");

        priceLbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        priceLbl.setText("--");

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel8.setText("Available No of Items:");

        availNoOfItemsLbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        availNoOfItemsLbl.setText("--");

        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(itemIdTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(priceLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(availNoOfItemsLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availNoOfItemsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(availNoOfItemsLbl))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(priceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIdTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(brandsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(showItemsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(noOfItemsSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mensRBtn)
                        .addGap(38, 38, 38)
                        .addComponent(ladiesRBtn)
                        .addGap(38, 38, 38)
                        .addComponent(kidsRBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mensRBtn)
                            .addComponent(ladiesRBtn)
                            .addComponent(kidsRBtn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noOfItemsSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jButton2.setBackground(new java.awt.Color(229, 228, 226));
        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton2.setText("Checkout");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(229, 228, 226));

        amountLbl.setBackground(new java.awt.Color(229, 228, 226));
        amountLbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 17)); // NOI18N
        amountLbl.setText("Amount");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(amountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        removeBtn.setBackground(new java.awt.Color(229, 228, 226));
        removeBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        removeBtn.setText("Remove from list");
        removeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removeBtn.setFocusPainted(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(96, 130, 182));

        jPanel5.setBackground(new java.awt.Color(96, 130, 182));

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(211, 211, 211));
        jLabel9.setText("CHECKOUT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Edit");

        createTableMBtn.setText("Edit Stocks");
        createTableMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTableMBtnActionPerformed(evt);
            }
        });
        jMenu1.add(createTableMBtn);

        jMenuItem1.setText("Generate Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jMenuItem2.setText("Veiw Stock");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createTableMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTableMBtnActionPerformed
        new EditStock().setVisible(true);
    }//GEN-LAST:event_createTableMBtnActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO addToTable your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
      /*  ResultSet rs = new UpdateController().updateBrandsCmb();
        brandsCmb.removeAllItems();
        try {

            while(rs.next()){

                brandsCmb.addItem(rs.getString("table_name"));

            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }*/
      

    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void kidsRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidsRBtnActionPerformed
        showItemsBtn.setEnabled(true);
    }//GEN-LAST:event_kidsRBtnActionPerformed

    private void showItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showItemsBtnActionPerformed
try {
            availNoOfItemsLbl.setText("--");
            ResultSet rs = new UpdateController().updateItemCmb(brandsCmb.getSelectedItem().toString().replace(' ', '_'),getCategoryRBtns());

            itemsCmb.removeAllItems();
            while(rs.next()){

                itemsCmb.addItem(rs.getString("item_name").replace('_', ' '));

            }

        } catch (SQLException ex) {
            Logger.getLogger(EditStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        itemsCmb.setEnabled(true);
                
    }//GEN-LAST:event_showItemsBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        
       AddToTableController.removefromTable(itemsTbl.getSelectedRow()); 
        int value =itemsTbl.getSelectedRow();
        
        
            
            Double totalInt = Double.parseDouble(total)-Double.parseDouble(dtm.getValueAt(itemsTbl.getSelectedRow(), 5).toString());
            
            total =  Double.toString(totalInt);
            amountLbl.setText(total);
            
        
        dtm.removeRow(itemsTbl.getSelectedRow());

    }//GEN-LAST:event_removeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        Vector v = AddToTableController.addToTable(itemIdTF.getText(), brandsCmb.getSelectedItem().toString(), itemsCmb.getSelectedItem().toString(),getCategoryRBtns(), noOfItemsSpnr.getValue().toString(),Integer.toString(Integer.parseInt(priceLbl.getText())*Integer.parseInt(noOfItemsSpnr.getValue().toString())) ,availNoOfItemsLbl.getText());
        if(!v.get(0).toString().equals("")){
            dtm.addRow(v);
            
            total = Double.toString(Double.parseDouble(total)+ (Double.parseDouble(priceLbl.getText())*Double.parseDouble(noOfItemsSpnr.getValue().toString())));
            amountLbl.setText(total);
            
            

        }

        
    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        Purchase purchase = new Purchase();
        PurchaseController.openPurchase(dtm.getDataVector().isEmpty(),dtm,amountLbl.getText());

            total =  "0";
            amountLbl.setText("Amount");
         
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void itemsCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsCmbActionPerformed
        addBtn.setEnabled(true);
    }//GEN-LAST:event_itemsCmbActionPerformed

    private void itemsCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemsCmbItemStateChanged
        try{

            availNoOfItemsLbl.setText(AddItemController.getNoOfItems(brandsCmb.getSelectedItem().toString().replace(' ', '_'),itemsCmb.getSelectedItem().toString().replace(' ', '_')));
            priceLbl.setText(AddItemController.getPrice(brandsCmb.getSelectedItem().toString().replace(' ', '_'),itemsCmb.getSelectedItem().toString().replace(' ', '_')));
            itemIdTF.setText(AddItemController.getitemId(brandsCmb.getSelectedItem().toString().replace(' ', '_'),itemsCmb.getSelectedItem().toString().replace(' ', '_')));
            
            
            
                addBtn.setEnabled(true);
            
            
        }
        catch(Exception ex){

            ex.printStackTrace();
            
        }
    }//GEN-LAST:event_itemsCmbItemStateChanged

    private void itemsCmbComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_itemsCmbComponentRemoved

        // TODO add your handling code here:
    }//GEN-LAST:event_itemsCmbComponentRemoved

    private void itemsCmbComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_itemsCmbComponentAdded

        try{

            availNoOfItemsLbl.setText(AddItemController.getNoOfItems(brandsCmb.getSelectedItem().toString().replace(' ', '_'),itemsCmb.getSelectedItem().toString().replace(' ', '_')));
            priceLbl.setText(AddItemController.getPrice(brandsCmb.getSelectedItem().toString().replace(' ', '_'),itemsCmb.getSelectedItem().toString().replace(' ', '_')));
            itemIdTF.setText(AddItemController.getitemId(brandsCmb.getSelectedItem().toString().replace(' ', '_'),itemsCmb.getSelectedItem().toString().replace(' ', '_')));
        }
        catch(Exception ex){

            ex.printStackTrace();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsCmbComponentAdded

    private void ladiesRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladiesRBtnActionPerformed
        showItemsBtn.setEnabled(true);
    }//GEN-LAST:event_ladiesRBtnActionPerformed

    private void mensRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensRBtnActionPerformed
        showItemsBtn.setEnabled(true);
    }//GEN-LAST:event_mensRBtnActionPerformed

    private void brandsCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandsCmbActionPerformed
        itemsCmb.setEnabled(false);
        
        
    }//GEN-LAST:event_brandsCmbActionPerformed

    private void brandsCmbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandsCmbMousePressed
  ResultSet rs = new UpdateController().updateBrandsCmb();
        brandsCmb.removeAllItems();
        try {

            while(rs.next()){

                brandsCmb.addItem(rs.getString("table_name").replace('_', ' '));

            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_brandsCmbMousePressed

    private void showItemsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showItemsBtnMouseClicked
        
    }//GEN-LAST:event_showItemsBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
     
            
        brandsCmb.setSelectedItem(null);
        itemsCmb.removeAllItems();
        amountLbl.setText("Amount");
        total = "0";
        clearTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void brandsCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brandsCmbItemStateChanged
        addBtn.setEnabled(false);
        itemsCmb.setEnabled(false);
    }//GEN-LAST:event_brandsCmbItemStateChanged

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered

    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
if(auth==false){
            
        brandsCmb.setSelectedItem(null);
        itemsCmb.removeAllItems();
        
        int i = 0;
            while(dtm.getRowCount()>i)
            {dtm.removeRow(i);}
            
            auth = true;
        }  


    }//GEN-LAST:event_jPanel3FocusGained

    private void jPanel3AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel3AncestorRemoved
    
    }//GEN-LAST:event_jPanel3AncestorRemoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
/*try {
            availNoOfItemsLbl.setText("--");
            ResultSet rs = new UpdateController().updateItemCmb(brandsCmb.getSelectedItem().toString(),getCategoryRBtns());

            itemsCmb.removeAllItems();
            while(rs.next()){

                itemsCmb.addItem(rs.getString("item_name"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(EditStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        itemsCmb.setEnabled(true);  */    
    }//GEN-LAST:event_jPanel3MouseMoved

    private void itemIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdTFActionPerformed
    try {
        Thread.sleep(2000);
    } catch (InterruptedException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
        Vector v = AddToTableController.addToTable(itemIdTF.getText(), brandsCmb.getSelectedItem().toString(), itemsCmb.getSelectedItem().toString(),getCategoryRBtns(), noOfItemsSpnr.getValue().toString(),Integer.toString(Integer.parseInt(priceLbl.getText())*Integer.parseInt(noOfItemsSpnr.getValue().toString())) ,availNoOfItemsLbl.getText());
        if(!v.get(0).toString().equals("")){
            dtm.addRow(v);
            
            total = Double.toString(Double.parseDouble(total)+ (Double.parseDouble(priceLbl.getText())*Double.parseDouble(noOfItemsSpnr.getValue().toString())));
            amountLbl.setText(total);
            
            

        }
    }//GEN-LAST:event_itemIdTFActionPerformed

    private void itemIdTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemIdTFKeyReleased
        
        
        
        System.out.println("hi");
        String[] rs = new String [6];
    try {
        rs = AddItemController.checkItemId(itemIdTF.getText());
        
             System.out.println("mee"+rs[2]);
                if(rs[2].equals("mens")){
                    System.out.println("mee"+rs[2]);
                    mensRBtn.setSelected(true);
                   
                }
                if(rs[2].equals("ladies")){
                    
                    ladiesRBtn.setSelected(true);
               
                }
                if(rs[2].equals("kids")){
                    
                    kidsRBtn.setSelected(true);
                   
                }
                showItemsBtn.setEnabled(true);
                itemsCmb.setEnabled(true);
                itemsCmb.setEditable(true);
                availNoOfItemsLbl.setText(rs[4]);
                priceLbl.setText(rs[3]);
                brandsCmb.setSelectedItem(rs[5]);
                itemsCmb.setSelectedItem(rs[1]);
                
                
                

           
        
    } catch (SQLException ex){
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
      
        
    
            //itemIdTF.setText(AddItemController.getitemId(brandsCmb.getSelectedItem().toString(),itemsCmb.getSelectedItem().toString()));
    }//GEN-LAST:event_itemIdTFKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println("generate excel");
    try {
        new PurchaseReport().setVisible(true);
    } catch (SQLException ex){
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemIdTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemIdTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdTFKeyTyped

    private void itemIdTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemIdTFKeyPressed
char key = evt.getKeyChar();
        if(Character.isDigit(key)||Character.isISOControl(key))
        {
            itemIdTF.setEditable(true);
        }
        else{itemIdTF.setEditable(false);}
    }//GEN-LAST:event_itemIdTFKeyPressed

    private void itemIdTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_itemIdTFCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdTFCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JLabel availNoOfItemsLbl;
    private javax.swing.JComboBox<String> brandsCmb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem createTableMBtn;
    private javax.swing.JTextField itemIdTF;
    private javax.swing.JComboBox<String> itemsCmb;
    private javax.swing.JTable itemsTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton kidsRBtn;
    private javax.swing.JRadioButton ladiesRBtn;
    private javax.swing.JRadioButton mensRBtn;
    private javax.swing.JSpinner noOfItemsSpnr;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton showItemsBtn;
    // End of variables declaration//GEN-END:variables

    private void DatabaseOperations() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
            new Home().setVisible(true);
        }
    }
    public static DefaultTableModel getDefaultTableModel(){
    
        
        
        return dtm;
    }
}
