/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AddItemController;
import Controller.UpdateController;
import Model.DatabaseOperations;
import static View.Home.dtm;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.div;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Adithya
 */
public class PurchaseReport extends javax.swing.JFrame {
    static DefaultTableModel dtm2;
    
    /**
     * Creates new form PurchaseReport
     */
    public PurchaseReport() throws SQLException {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        columnCmb.removeAllItems();
        
        columnCmb.addItem("purchase id");
        columnCmb.addItem("item name");
        columnCmb.addItem("brand name");
        columnCmb.addItem("item id");
        columnCmb.addItem("date time");
        columnCmb.addItem("dates between");
        columnCmb.addItem("no of items");
        columnCmb.addItem("price");
        
        searchTF.setVisible(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        purchaseReportsTbl = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fullGenBtn = new javax.swing.JButton();
        dailyGenBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        columnCmb = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        purchaseReportsTbl.setBackground(new java.awt.Color(96, 130, 182));
        purchaseReportsTbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        purchaseReportsTbl.setForeground(new java.awt.Color(239, 238, 236));
        purchaseReportsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Purchase ID", "Item ID", "Brand Name", "Item Name", "Date-Time", "No. of Items", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purchaseReportsTbl.setGridColor(new java.awt.Color(176, 176, 218));
        purchaseReportsTbl.setRowHeight(25);
        purchaseReportsTbl.setRowMargin(5);
        purchaseReportsTbl.setSelectionBackground(new java.awt.Color(0, 0, 102));
        purchaseReportsTbl.setSelectionForeground(new java.awt.Color(242, 233, 232));
        purchaseReportsTbl.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(purchaseReportsTbl);

        jPanel5.setBackground(new java.awt.Color(96, 130, 182));

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(211, 211, 211));
        jLabel12.setText("PURCHASE REPORT");

        fullGenBtn.setBackground(new java.awt.Color(229, 228, 226));
        fullGenBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        fullGenBtn.setText("Generate Full Report");
        fullGenBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fullGenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullGenBtnActionPerformed(evt);
            }
        });

        dailyGenBtn.setBackground(new java.awt.Color(229, 228, 226));
        dailyGenBtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        dailyGenBtn.setText("Generate Daily Report");
        dailyGenBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dailyGenBtn.setFocusPainted(false);
        dailyGenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyGenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dailyGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fullGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(229, 228, 226));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton1.setText("Remove");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        columnCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        columnCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                columnCmbItemStateChanged(evt);
            }
        });
        columnCmb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                columnCmbFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                columnCmbFocusLost(evt);
            }
        });
        columnCmb.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                columnCmbPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(columnCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(columnCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
       
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void fullGenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullGenBtnActionPerformed
        dtm2 = (DefaultTableModel)purchaseReportsTbl.getModel();
        dtm2.setRowCount(0);
        int i = 0;
        while(dtm2.getRowCount()>i){
            dtm2.removeRow(i);
            i++;
        }
        
        
        try {
            ResultSet rs = DatabaseOperations.getPurchaseReport();
            while(rs.next()){
                Vector v = new Vector();
                v.add(0,rs.getString("purchase_id"));
                v.add(1,rs.getString("item_id"));
                v.add(2,rs.getString("brand_name"));
                v.add(3,rs.getString("item_name"));
                v.add(4,rs.getString("date_time"));
                v.add(5,rs.getString("no_of_items"));
                v.add(6,rs.getString("price"));
                
                System.out.println(v.get(0));
                if(!v.get(0).toString().equals("")){
                    
                    dtm2.addRow(v);
                    //v.clear();
                //System.out.println(v.get(0)+" after");
                }
                
                //purchaseReportTbl.updateUI();
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                // TODO add your handling code here:
    }//GEN-LAST:event_fullGenBtnActionPerformed

    private void dailyGenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyGenBtnActionPerformed
        dtm2 = (DefaultTableModel)purchaseReportsTbl.getModel();
        dtm2.setRowCount(0);
        int i = 0;
        while(dtm2.getRowCount()>i){
            dtm2.removeRow(i);
            i++;
        }
        
        
        try {
            ResultSet rs = DatabaseOperations.getDailyPurchaseReport();
            while(rs.next()){
                Vector v = new Vector();
                v.add(0,rs.getString("purchase_id"));
                v.add(1,rs.getString("item_id"));
                v.add(2,rs.getString("brand_name").replace('_', ' '));
                v.add(3,rs.getString("item_name").replace('_', ' '));
                v.add(4,rs.getString("date_time"));
                v.add(5,rs.getString("no_of_items"));
                v.add(6,rs.getString("price"));
                System.out.println(v.get(0));
                if(!v.get(0).toString().equals("")){
                    
                    dtm2.addRow(v);
                    //v.clear();
                //System.out.println(v.get(0)+" after");
                }
                
                //purchaseReportTbl.updateUI();
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_dailyGenBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String purchaseId = (String) purchaseReportsTbl.getValueAt(purchaseReportsTbl.getSelectedRow(),0);
        String itemId = (String) purchaseReportsTbl.getValueAt(purchaseReportsTbl.getSelectedRow(),1);
        String BrandName = (String) purchaseReportsTbl.getValueAt(purchaseReportsTbl.getSelectedRow(),2);
        String noOfItems = (String) purchaseReportsTbl.getValueAt(purchaseReportsTbl.getSelectedRow(),4);
        
        try {
            DatabaseOperations.removePurchase( purchaseId, itemId );
            dtm2.removeRow(purchaseReportsTbl.getSelectedRow());
            AddItemController.setNoOfItemsAddId(BrandName,itemId,noOfItems);
            System.out.println(purchaseId+itemId+BrandName+noOfItems);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        dtm2 = (DefaultTableModel)purchaseReportsTbl.getModel();
        dtm2.setRowCount(0);
        int i = 0;
        while(dtm2.getRowCount()>i){
            dtm2.removeRow(i);
            i++;
        }
        if(columnCmb.getSelectedItem().toString().toLowerCase().equals("dates between")){
            
            String dates = searchTF.getText().replace(" ","");
            String datesFromTo[]=dates.split(":");
            String from = datesFromTo[0];
            String to = datesFromTo[1];
            System.out.println(from+ to);
            try {
                ResultSet rs = DatabaseOperations.getBetweenDatesPurchaseReport(from, to);
                
                while(rs.next()){
                System.out.println(rs.getString("purchase_id"));
                Vector v = new Vector();
                v.add(0,rs.getString("purchase_id"));
                v.add(1,rs.getString("item_id"));
                v.add(2,rs.getString("brand_name").replace('_', ' '));
                v.add(3,rs.getString("item_name").replace('_', ' '));
                v.add(4,rs.getString("date_time"));
                v.add(5,rs.getString("no_of_items"));
                v.add(6,rs.getString("price"));
                System.out.println(v.get(0));
                if(!v.get(0).toString().equals("")){
                    
                    dtm2.addRow(v);
                    //v.clear();
                //System.out.println(v.get(0)+" after");
                }
                
                //purchaseReportTbl.updateUI();
                
            }
            } catch (SQLException ex) {
                Logger.getLogger(PurchaseReport.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
        
        
        
        try {
            ResultSet rs = DatabaseOperations.getSearchPurchaseReport(searchTF.getText().toString().replace(" ","_"), columnCmb.getSelectedItem().toString().toLowerCase().replace(" ","_"));
        ;
            while(rs.next()){
                System.out.println(rs.getString("purchase_id"));
                Vector v = new Vector();
                v.add(0,rs.getString("purchase_id"));
                v.add(1,rs.getString("item_id"));
                v.add(2,rs.getString("brand_name").replace('_', ' '));
                v.add(3,rs.getString("item_name").replace('_', ' '));
                v.add(4,rs.getString("date_time"));
                v.add(5,rs.getString("no_of_items"));
                v.add(6,rs.getString("price"));
                System.out.println(v.get(0));
                if(!v.get(0).toString().equals("")){
                    
                    dtm2.addRow(v);
                    //v.clear();
                //System.out.println(v.get(0)+" after");
                }
                
                //purchaseReportTbl.updateUI();
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void columnCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_columnCmbItemStateChanged
         
    }//GEN-LAST:event_columnCmbItemStateChanged

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void columnCmbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_columnCmbFocusGained
        
    }//GEN-LAST:event_columnCmbFocusGained

    private void columnCmbPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_columnCmbPopupMenuWillBecomeInvisible
        if(columnCmb.getSelectedItem().toString().toLowerCase().equals("dates between")){
           searchTF.setText("2000-00-00 : 2000-00-00");
           
           
       }
    }//GEN-LAST:event_columnCmbPopupMenuWillBecomeInvisible

    private void columnCmbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_columnCmbFocusLost
        
    }//GEN-LAST:event_columnCmbFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PurchaseReport().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PurchaseReport.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> columnCmb;
    private javax.swing.JButton dailyGenBtn;
    private javax.swing.JButton fullGenBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable purchaseReportsTbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTF;
    // End of variables declaration//GEN-END:variables
}
